# https://docs.haskellstack.org/en/stable/configure/yaml/project/#snapshot
# https://docs.haskellstack.org/en/stable/configure/yaml/project/#resolver
resolver: ghc-9.10.1
packages:
  - free-foil-stlc
  - free-foil-exercises
notify-if-nix-on-path: false
