-- File generated by the BNF Converter (bnfc 2.9.6).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Language.

module Language.ModularSTLC.Syntax.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Language.ModularSTLC.Syntax.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Language.ModularSTLC.Syntax.Abs.Var where
  prt _ (Language.ModularSTLC.Syntax.Abs.Var i) = doc $ showString i
instance Print Language.ModularSTLC.Syntax.Abs.ModuleName where
  prt _ (Language.ModularSTLC.Syntax.Abs.ModuleName i) = doc $ showString i
instance Print (Language.ModularSTLC.Syntax.Abs.Program' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.Program _ statements -> prPrec i 0 (concatD [prt 0 statements])

instance Print (Language.ModularSTLC.Syntax.Abs.ImportItem' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.ImportItemGlob _ -> prPrec i 0 (concatD [doc (showString "*")])
    Language.ModularSTLC.Syntax.Abs.ImportItemGlobAs _ modulename -> prPrec i 0 (concatD [doc (showString "*"), doc (showString "as"), prt 0 modulename])
    Language.ModularSTLC.Syntax.Abs.ImportItemNames _ importitemnames -> prPrec i 0 (concatD [doc (showString "{"), prt 0 importitemnames, doc (showString "}")])

instance Print (Language.ModularSTLC.Syntax.Abs.ImportItemName' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.ImportItemNameModule _ modulename -> prPrec i 0 (concatD [prt 0 modulename])
    Language.ModularSTLC.Syntax.Abs.ImportItemNameVar _ var -> prPrec i 0 (concatD [prt 0 var])

instance Print [Language.ModularSTLC.Syntax.Abs.ImportItemName' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Language.ModularSTLC.Syntax.Abs.Location' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.LocationLocal _ modulename -> prPrec i 0 (concatD [prt 0 modulename])
    Language.ModularSTLC.Syntax.Abs.LocationPath _ str -> prPrec i 0 (concatD [printString str])

instance Print (Language.ModularSTLC.Syntax.Abs.Statement' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.StatementModule _ modulename statements -> prPrec i 0 (concatD [doc (showString "module"), prt 0 modulename, doc (showString "where"), doc (showString "{"), prt 0 statements, doc (showString "}")])
    Language.ModularSTLC.Syntax.Abs.StatementImportLocal _ importitem location -> prPrec i 0 (concatD [doc (showString "import"), prt 0 importitem, doc (showString "from"), prt 0 location])
    Language.ModularSTLC.Syntax.Abs.StatementFunSig _ var type_ -> prPrec i 0 (concatD [prt 0 var, doc (showString ":"), prt 0 type_])
    Language.ModularSTLC.Syntax.Abs.StatementFun _ var exp -> prPrec i 0 (concatD [prt 0 var, doc (showString "="), prt 0 exp])
    Language.ModularSTLC.Syntax.Abs.StatementFunWhere _ var exp statements -> prPrec i 0 (concatD [prt 0 var, doc (showString "="), prt 0 exp, doc (showString "where"), doc (showString "{"), prt 0 statements, doc (showString "}")])
    Language.ModularSTLC.Syntax.Abs.StatementExport _ exportitems -> prPrec i 0 (concatD [doc (showString "export"), prt 0 exportitems])
    Language.ModularSTLC.Syntax.Abs.StatementCommandTypeCheck _ expunderctx type_ -> prPrec i 0 (concatD [doc (showString "#typecheck"), prt 0 expunderctx, doc (showString "<="), prt 0 type_])
    Language.ModularSTLC.Syntax.Abs.StatementCommandTypeSynth _ expunderctx synthresult -> prPrec i 0 (concatD [doc (showString "#typesynth"), prt 0 expunderctx, doc (showString "=>"), prt 0 synthresult])

instance Print (Language.ModularSTLC.Syntax.Abs.ExportItem' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.ExportItemModuleName _ modulename -> prPrec i 0 (concatD [prt 0 modulename])
    Language.ModularSTLC.Syntax.Abs.ExportItemVar _ var -> prPrec i 0 (concatD [prt 0 var])

instance Print [Language.ModularSTLC.Syntax.Abs.ExportItem' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Language.ModularSTLC.Syntax.Abs.Statement' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print (Language.ModularSTLC.Syntax.Abs.SynthResult' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.SynthResultType _ type_ -> prPrec i 0 (concatD [doc (showString "!"), prt 0 type_])
    Language.ModularSTLC.Syntax.Abs.SynthResultUnknown _ -> prPrec i 0 (concatD [doc (showString "?")])

instance Print (Language.ModularSTLC.Syntax.Abs.Exp' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.ExpApp _ exp1 exp2 -> prPrec i 1 (concatD [doc (showString "("), prt 0 exp1, doc (showString ")"), prt 0 exp2])
    Language.ModularSTLC.Syntax.Abs.ExpAbs _ var exp -> prPrec i 2 (concatD [doc (showString "\\"), prt 0 var, doc (showString "."), prt 0 exp])
    Language.ModularSTLC.Syntax.Abs.ExpPlus _ exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "+"), prt 4 exp2])
    Language.ModularSTLC.Syntax.Abs.ExpVar _ var -> prPrec i 4 (concatD [prt 0 var])
    Language.ModularSTLC.Syntax.Abs.ExpNumber _ n -> prPrec i 5 (concatD [prt 0 n])
    Language.ModularSTLC.Syntax.Abs.ExpAccessor _ accessors -> prPrec i 6 (concatD [doc (showString "#"), prt 0 accessors])

instance Print (Language.ModularSTLC.Syntax.Abs.Accessor' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.AccessorModuleName _ modulename -> prPrec i 0 (concatD [prt 0 modulename])
    Language.ModularSTLC.Syntax.Abs.AccessorVar _ var -> prPrec i 0 (concatD [prt 0 var])

instance Print [Language.ModularSTLC.Syntax.Abs.Accessor' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "."), prt 0 xs]

instance Print (Language.ModularSTLC.Syntax.Abs.Type' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.TypeUnit _ -> prPrec i 1 (concatD [doc (showString "Int")])
    Language.ModularSTLC.Syntax.Abs.TypeFunc _ type_1 type_2 -> prPrec i 2 (concatD [prt 0 type_1, doc (showString "->"), prt 0 type_2])

instance Print (Language.ModularSTLC.Syntax.Abs.CtxVar' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.CtxVar _ var type_ -> prPrec i 0 (concatD [prt 0 var, doc (showString ":"), prt 0 type_])

instance Print [Language.ModularSTLC.Syntax.Abs.CtxVar' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Language.ModularSTLC.Syntax.Abs.Ctx' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.Ctx _ ctxvars -> prPrec i 0 (concatD [prt 0 ctxvars])

instance Print (Language.ModularSTLC.Syntax.Abs.ExpUnderCtx' a) where
  prt i = \case
    Language.ModularSTLC.Syntax.Abs.ExpUnderCtx _ ctx exp -> prPrec i 0 (concatD [prt 0 ctx, doc (showString "|-"), prt 0 exp])
