name: free-foil-stlc
synopsis: "An implementation of simply typed lambda calculus using Free Foil"
version: 0.0.1
github: "deemp/query-driven-free-foil"
license: BSD3
author: "Danila Danko, Nickolay Kudasov, Nikita Strygin"
maintainer: "br4ch1st0chr0n3@gmail.com, nickolay.kudasov@gmail.com"
copyright: "2024 Danila Danko, Nickolay Kudasov, Nikita Strygin"

extra-source-files:
  - README.md
  - CHANGELOG.md
  - grammar/STLC/Syntax.cf

verbatim:
  cabal-version: 1.24

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/objectionary/eo-phi-normalizer#readme>

custom-setup:
  dependencies:
    - base >= 4.11.0.0 && < 5.0
    - Cabal >= 2.4.0.1 && < 4.0
    - process >= 1.6.3.0

build-tools:
  alex: "== 3.4.0.1"
  happy: "== 1.20.1.1"
  BNFC:bnfc: "== 2.9.5"

dependencies:
  - base >= 4.7 && < 5
  - array >= 0.5.5.0

default-extensions:
  - ImportQualifiedPost

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-missing-export-lists

library:
  source-dirs: src
  when:
    - condition: false
      other-modules:
        - Language.STLC.Syntax.Test
        - Language.STLC.Syntax.ErrM
        - Language.STLC.Syntax.Skel

executables:
  free-foil-stlc:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - free-foil-stlc
      - with-utf8